import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
await fs.mkdir('artifacts',{recursive:true});await fs.mkdir('models',{recursive:true});
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist','--disable-gpu-sandbox','--no-sandbox']});
const page=await browser.newPage({viewport:{width:1600,height:1000},deviceScaleFactor:1,acceptDownloads:true});
const errors=[],failedRequests=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failedRequests.push(`${r.status()} ${r.url()}`);});
await page.goto('http://127.0.0.1:5173/?qa',{waitUntil:'networkidle'});
await page.waitForFunction(()=>window.__afterlight?.state==='menu',null,{timeout:60000});
await page.waitForTimeout(800);
const gpu=await page.evaluate(()=>{const gl=document.querySelector('#scene').getContext('webgl2');const ext=gl.getExtension('WEBGL_debug_renderer_info');return ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER);});
await page.screenshot({path:'artifacts/01-menu.png'});
const exports=[];
for(const model of ['aurora','kasumi','vesper']){
 await page.locator(`[data-model="${model}"]`).click();
 await page.locator('#showroom').click();
 await page.waitForTimeout(500);
 if(model==='aurora')await page.screenshot({path:'artifacts/02-studio.png'});
 if(model==='vesper')await page.screenshot({path:'artifacts/07-vesper.png'});
 const downloadPromise=page.waitForEvent('download');
 await page.locator('#export-model').click();const dl=await downloadPromise;
 const path=`models/${dl.suggestedFilename()}`;await dl.saveAs(path);
 const bytes=await fs.readFile(path);assert.equal(bytes.toString('utf8',0,4),'glTF');assert.equal(bytes.readUInt32LE(4),2);
 exports.push({model,bytes:bytes.length});
 await page.locator('#studio-back').click();
}
await page.locator('[data-model="aurora"]').click();
await page.locator('#showroom').click();await page.locator('[data-view="wheel"]').click();
await page.waitForTimeout(1300);await page.screenshot({path:'artifacts/03-wheel.png'});
await page.locator('#studio-back').click();
await page.locator('#play').click();await page.locator('#start-race').click();
await page.waitForFunction(()=>window.__afterlight.state==='racing',null,{timeout:30000});
await page.keyboard.down('KeyW');await page.waitForTimeout(2200);await page.keyboard.up('KeyW');
const movement=await page.evaluate(()=>window.__afterlight.telemetry);assert.ok(movement.drivers.at(-1).speed>5);
await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>window.__afterlight.state),'paused');
const frozen=await page.evaluate(()=>window.__afterlight.telemetry.raceTime);await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>window.__afterlight.telemetry.raceTime),frozen);
await page.locator('#resume').click();await page.keyboard.press('KeyR');
assert.equal(await page.evaluate(()=>window.__afterlight.telemetry.drivers.at(-1).penalty),3);
const halfway=await page.evaluate(()=>window.__afterlight.qaDrive(38));
await page.waitForTimeout(600);await page.screenshot({path:'artifacts/06-driving.png'});
const finished=await page.evaluate(()=>window.__afterlight.qaDrive(125));
assert.equal(finished.state,'finished');assert.ok(finished.drivers.every(d=>d.finishTime!==null&&d.lap===2));
await page.screenshot({path:'artifacts/08-results.png'});
assert.ok((await page.locator('#record-note').textContent()).includes('3 秒'));
await page.locator('#result-home').click();await page.locator('#play').click();
await page.locator('#mode').selectOption('time');await page.locator('#start-race').click();
const timeTrial=await page.evaluate(()=>window.__afterlight.qaDrive(100));
assert.equal(timeTrial.state,'finished');assert.equal(timeTrial.drivers.length,1);assert.equal(timeTrial.drivers[0].lap,1);
assert.equal(await page.locator('#result-position').textContent(),'TIME ATTACK');
await page.locator('#result-home').click();await page.locator('#nav-settings').click();
await page.locator('#quality').selectOption('low');await page.locator('#voice-enabled').uncheck();await page.locator('[data-close="settings-modal"]').click();
await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>window.__afterlight?.state==='menu',null,{timeout:60000});
await page.locator('#nav-settings').click();assert.equal(await page.locator('#quality').inputValue(),'low');assert.equal(await page.locator('#voice-enabled').isChecked(),false);
await page.locator('#quality').selectOption('medium');await page.locator('#voice-enabled').check();await page.locator('[data-close="settings-modal"]').click();
await page.setViewportSize({width:1280,height:720});await page.waitForTimeout(600);await page.screenshot({path:'artifacts/09-menu-720p.png'});
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(400);await page.screenshot({path:'artifacts/10-menu-mobile.png'});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
const report={gpu,exports,movement,halfway,finished,timeTrial,errors,failedRequests};
await fs.writeFile('artifacts/acceptance.json',JSON.stringify(report,null,2));
console.log(JSON.stringify({gpu,exports,raceCompleted:finished.drivers.length,timeTrialCompleted:timeTrial.drivers.length,errors,failedRequests},null,2));
await browser.close();assert.deepEqual(errors,[]);assert.deepEqual(failedRequests,[]);
