import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist','--disable-gpu-sandbox','--no-sandbox']});
const report={checks:[],performance:[],errors:[]};
try{
const p=await b.newPage({viewport:{width:1440,height:900}});p.on('pageerror',e=>report.errors.push(e.message));p.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});
await p.goto(process.env.AFTERLIGHT_URL||'http://127.0.0.1:5173/?qa');await p.waitForFunction(()=>window.__afterlight?.state==='menu',null,{timeout:90000});
const telemetry=()=>p.evaluate(()=>__afterlight.telemetry);
const open=async()=>{await p.locator('#open-garage').click();await p.waitForFunction(()=>__afterlight.telemetry.garage.thumbnails===5);};
const preview=async id=>{await p.locator(`[data-garage-model="${id}"]`).click();await p.waitForFunction(id=>__afterlight.telemetry.garage.preview===id&&!__afterlight.telemetry.garage.pending,id);await p.waitForTimeout(220);};
await open();assert.equal(await p.locator('[data-garage-model]').count(),5);assert.equal(await p.locator('.garage-empty').count(),1);assert.equal(await p.locator('.garage-empty button').count(),0);
await preview('tempest');assert.equal((await telemetry()).model,'aurora');await p.locator('[data-garage-color="#983e39"]').click();await p.keyboard.press('Escape');assert.equal((await telemetry()).paint,'#b8d9cf');await open();await preview('tempest');assert.equal((await telemetry()).garage.paint,'#885547');report.checks.push('five cards, inert sixth, preview does not apply, Esc cancels paint');
for(const id of ['aurora','kasumi','vesper','nightslash','tempest']){
 await preview(id);await p.locator('[data-garage-color="#547d91"]').click();await p.keyboard.press('Enter');assert.equal((await telemetry()).model,id);assert.equal((await telemetry()).paint,'#547d91');await p.locator('#theme').selectOption('night');await p.locator('#start-race').click();await p.waitForFunction(()=>__afterlight.state==='racing',null,{timeout:90000});
 await p.keyboard.down('KeyW');await p.waitForTimeout(1300);await p.keyboard.up('KeyW');assert.ok((await telemetry()).drivers[0].speed>0);await p.keyboard.press('KeyL');assert.equal((await telemetry()).lightMode,2);
 if(['nightslash','tempest'].includes(id)){await p.keyboard.press('KeyC');await p.waitForTimeout(400);await p.screenshot({path:`artifacts/garage/${id}-cockpit.png`});}
 await p.keyboard.press('Escape');await p.locator('#quit').click();await open();report.checks.push(`${id}: confirm paint, enter race, accelerate, headlights`);console.log('driving passed',id);
}
await p.keyboard.press('ArrowRight');await p.waitForTimeout(250);assert.equal((await telemetry()).garage.preview,'aurora');await p.keyboard.press('ArrowLeft');await p.waitForTimeout(250);assert.equal((await telemetry()).garage.preview,'tempest');
for(const id of ['nightslash','aurora','vesper','tempest'])await p.locator(`[data-garage-model="${id}"]`).click();await p.waitForTimeout(350);assert.equal(await p.locator('#garage-name').textContent(),'TEMPEST');
const before=(await telemetry()).garage.camera;const box=await p.locator('#garage-stage').boundingBox();await p.mouse.move(box.x+box.width/2,box.y+box.height/2);await p.mouse.down();await p.mouse.move(box.x+box.width/2+160,box.y+box.height/2+20,{steps:15});await p.mouse.up();await p.waitForTimeout(300);assert.notDeepEqual((await telemetry()).garage.camera,before);await p.mouse.wheel(0,-250);await p.waitForTimeout(300);await p.locator('[data-garage-view="wheel"]').click();await p.waitForTimeout(1200);await p.locator('[data-garage-view="orbit"]').click();await p.waitForTimeout(1200);
await p.screenshot({path:'artifacts/garage/garage-desktop.png'});report.checks.push('keyboard wrapping, rapid switching, drag, zoom, camera presets');
await p.waitForTimeout(300);const baseline=(await telemetry()).garage;for(let i=0;i<8;i++){await p.keyboard.press('Escape');await open();await preview('nightslash');await preview('tempest');}const after=(await telemetry()).garage;assert.equal(after.geometries,baseline.geometries);assert.equal(after.textures,baseline.textures);report.memory={baseline,after};
for(const id of ['nightslash','tempest']){await preview(id);await p.waitForTimeout(600);const a=await telemetry(),t=Date.now();await p.waitForTimeout(3000);const z=await telemetry();report.performance.push({id,fps:(z.frameCount-a.frameCount)*1000/(Date.now()-t),drawCalls:z.drawCalls,triangles:z.triangles});}
await p.keyboard.press('Escape');await p.reload();await p.waitForFunction(()=>window.__afterlight?.state==='menu',null,{timeout:90000});assert.equal((await telemetry()).model,'tempest');assert.equal((await telemetry()).paint,'#547d91');report.checks.push('repeated garage resource counts stable, confirmed selection survives reload');
await p.setViewportSize({width:390,height:844});await open();await preview('nightslash');await p.locator('#garage-confirm').scrollIntoViewIfNeeded();await p.screenshot({path:'artifacts/garage/garage-mobile.png'});await p.locator('#garage-confirm').click();assert.equal((await telemetry()).model,'nightslash');report.checks.push('390x844 layout: scroll cards and confirm');
report.gpu=await p.evaluate(()=>{const gl=document.querySelector('#scene').getContext('webgl2'),ex=gl.getExtension('WEBGL_debug_renderer_info');return ex?gl.getParameter(ex.UNMASKED_RENDERER_WEBGL):'unavailable';});report.browser=await b.version();report.viewport='1440x900 DPR 1, medium, headless Chrome';assert.equal(report.errors.length,0);console.log(JSON.stringify(report,null,2));
}finally{await fs.writeFile('artifacts/garage/validation.json',JSON.stringify(report,null,2));await b.close();}
