import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
await fs.mkdir('artifacts/start-flow',{recursive:true});const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist','--no-sandbox']});const report={errors:[],transitions:[]};
try{const p=await b.newPage({viewport:{width:1440,height:900}});p.on('pageerror',e=>report.errors.push(e.message));p.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});await p.goto('http://127.0.0.1:4180/');await p.waitForFunction(()=>window.__afterlight?.state==='menu',null,{timeout:90000});assert.equal(await p.evaluate(()=>__afterlight.track.id),'harbor');assert.deepEqual(await p.locator('#circuit option').evaluateAll(os=>os.map(o=>o.value)),['harbor','coast','mountain']);await p.locator('#play').hover();await p.waitForTimeout(300);report.hover=await p.locator('#play').evaluate(e=>getComputedStyle(e).transform);assert.ok(parseFloat(report.hover.split('(')[1])>1);await p.screenshot({path:'artifacts/start-flow/harbor-home.png'});
for(const id of ['harbor','coast','mountain']){
 await p.locator('#play').click();await p.locator('#circuit').selectOption(id);await p.locator('#theme').selectOption('day');await p.locator('#start-race').click();await p.waitForFunction(()=>__afterlight.state==='intro');
 await p.evaluate(()=>{window.landingFrames=[];let prev;const sample=()=>{const t=__afterlight.telemetry,cur={state:t.state,position:t.cameraPosition,q:t.cameraQuaternion,fov:t.cameraFov,time:t.introTime};if(prev?.state==='intro'&&cur.state==='countdown')window.landingFrames.push({before:prev,after:cur});prev=cur;if(['intro','countdown'].includes(t.state))requestAnimationFrame(sample);};sample();});
 if(id==='coast'){await p.waitForTimeout(1500);await p.locator('#intro-skip').click();}else if(id==='mountain'){await p.waitForTimeout(1200);await p.keyboard.press('Space');}
 await p.waitForFunction(()=>__afterlight.state==='countdown',null,{timeout:30000});await p.waitForTimeout(100);const pair=await p.evaluate(()=>landingFrames[0]);assert.ok(pair);const delta=Math.hypot(...pair.before.position.map((x,i)=>x-pair.after.position[i]));assert.ok(delta<2,`endpoint jump ${delta}`);assert.ok(Math.abs(pair.before.fov-pair.after.fov)<.1);report.transitions.push({id,delta,angleDot:Math.abs(pair.before.q.reduce((a,x,i)=>a+x*pair.after.q[i],0))});await p.screenshot({path:`artifacts/start-flow/${id}-landing.png`});await p.waitForFunction(()=>__afterlight.state==='racing');await p.keyboard.down('KeyW');await p.waitForTimeout(2200);await p.keyboard.up('KeyW');await p.screenshot({path:`artifacts/start-flow/${id}-launch.png`});const t=await p.evaluate(()=>__afterlight.telemetry);assert.deepEqual(t.visibleWorlds,[id]);assert.ok(t.drivers.filter(d=>d.id!=='player').every(d=>Math.abs(d.targetLane)>=2.9));await p.keyboard.press('Escape');await p.locator('#quit').click();console.log('PASS',id,delta);
}
assert.deepEqual(report.errors,[]);console.log(JSON.stringify(report,null,2));}finally{await fs.writeFile('artifacts/start-flow/results.json',JSON.stringify(report,null,2));await b.close();}
