import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist','--disable-gpu-sandbox','--no-sandbox']});
const page=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173/?qa',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__afterlight?.state==='menu');
await page.locator('#play').click();await page.locator('#mode').selectOption('time');await page.locator('#start-race').click();
await page.waitForFunction(()=>window.__afterlight.state==='racing');
await page.keyboard.down('KeyW');await page.waitForTimeout(3200);await page.keyboard.up('KeyW');
const before=await page.evaluate(()=>window.__afterlight.telemetry.drivers.at(-1));
await page.keyboard.down('Space');await page.waitForTimeout(45);await page.keyboard.up('Space');await page.waitForTimeout(250);
const after=await page.evaluate(()=>window.__afterlight.telemetry);assert.ok(after.drivers.at(-1).speed<before.speed-6);assert.ok(after.smoke>0);
await page.screenshot({path:'artifacts/update-handbrake.png'});
await page.keyboard.press('KeyC');await page.waitForTimeout(700);await page.screenshot({path:'artifacts/update-cockpit.png'});
const cockpit=await page.evaluate(()=>window.__afterlight.telemetry);assert.equal(cockpit.cameraMode,1);assert.equal(cockpit.cameraLayers,5);
await page.keyboard.press('Escape');await page.locator('#quit').click();
const cockpitModels=[];
for(const model of ['kasumi','vesper']){
 await page.locator(`[data-model="${model}"]`).click();await page.locator('#play').click();await page.locator('#start-race').click();await page.keyboard.press('KeyC');await page.waitForTimeout(600);
 await page.screenshot({path:`artifacts/update-cockpit-${model}.png`});cockpitModels.push(await page.evaluate(()=>window.__afterlight.telemetry.cameraLayers));
 await page.keyboard.press('Escape');await page.locator('#quit').click();
}
await page.locator('[data-model="aurora"]').click();await page.locator('#play').click();await page.locator('#mode').selectOption('race');await page.locator('#start-race').click();
await page.evaluate(()=>window.__afterlight.qaDrive(5));await page.evaluate(()=>window.__afterlight.qaArrangePass());
await page.keyboard.down('KeyW');await page.waitForFunction(()=>window.__afterlight.telemetry.stats.overtakes>0,null,{timeout:10000});await page.keyboard.up('KeyW');
await page.waitForTimeout(350);await page.screenshot({path:'artifacts/update-overtake.png'});
assert.ok((await page.locator('#pass-label').textContent()).includes('超越'));
await page.keyboard.press('Escape');await page.locator('#restart').click();
const halfway=await page.evaluate(()=>window.__afterlight.qaDrive(45));await page.waitForTimeout(700);await page.screenshot({path:'artifacts/update-hud.png'});
const finished=await page.evaluate(()=>window.__afterlight.qaDrive(130));assert.ok(finished.stats.average>50);assert.ok(finished.stats.top>100);assert.ok(finished.finishSequence);
await page.waitForTimeout(1800);await page.screenshot({path:'artifacts/update-finish-close.png'});
const cameraA=await page.evaluate(()=>window.__afterlight.telemetry.cameraPosition);await page.waitForTimeout(3800);
const cameraB=await page.evaluate(()=>window.__afterlight.telemetry.cameraPosition);assert.notDeepEqual(cameraA,cameraB);
await page.screenshot({path:'artifacts/update-finish-orbit.png'});
await page.waitForSelector('#result-modal:not([hidden])',{timeout:15000});await page.waitForTimeout(1400);await page.screenshot({path:'artifacts/update-results.png'});
assert.ok(Number(await page.locator('#result-average').textContent())>50);
const frozen=await page.evaluate(()=>window.__afterlight.telemetry.stats);await page.waitForTimeout(500);assert.deepEqual(await page.evaluate(()=>window.__afterlight.telemetry.stats),frozen);
await page.setViewportSize({width:1280,height:720});await page.waitForTimeout(300);await page.screenshot({path:'artifacts/update-results-720p.png'});
await fs.writeFile('artifacts/update-qa.json',JSON.stringify({before,after,cockpit,cockpitModels,halfway,finished,cameraA,cameraB,errors},null,2));console.log(JSON.stringify({tapDropKmh:(before.speed-after.drivers.at(-1).speed)*3.6,smoke:after.smoke,cockpitLayers:cockpit.cameraLayers,stats:finished.stats,state:finished.state,errors},null,2));
await browser.close();assert.deepEqual(errors,[]);
