import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
await fs.mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist','--disable-gpu-sandbox','--no-sandbox']});
const page=await browser.newPage({viewport:{width:1600,height:1000},deviceScaleFactor:1});
const issues=[];
page.on('pageerror',e=>issues.push(e.message));
page.on('console',m=>{if(m.type()==='error')issues.push(m.text());});
await page.goto('http://127.0.0.1:5173',{waitUntil:'networkidle'});
await page.waitForFunction(()=>window.__afterlight?.state==='menu',{timeout:60000});
await page.waitForTimeout(1600);
await page.screenshot({path:'artifacts/01-menu.png'});
console.log('menu',await page.evaluate(()=>window.__afterlight.telemetry));
await page.locator('#showroom').click();
await page.waitForTimeout(1100);
await page.screenshot({path:'artifacts/02-studio.png'});
await page.locator('[data-view="wheel"]').click();
await page.waitForTimeout(1400);
await page.screenshot({path:'artifacts/03-wheel.png'});
await page.locator('#studio-back').click();
await page.locator('#play').click();
await page.screenshot({path:'artifacts/04-briefing.png'});
await page.locator('#start-race').click();
await page.waitForTimeout(800);
await page.screenshot({path:'artifacts/05-grid.png'});
await page.waitForFunction(()=>window.__afterlight.state==='racing',{timeout:60000});
await page.keyboard.down('KeyW');
await page.waitForTimeout(7000);
await page.keyboard.up('KeyW');
await page.screenshot({path:'artifacts/06-driving.png'});
console.log('driving',await page.evaluate(()=>window.__afterlight.telemetry));
await page.keyboard.press('Escape');
console.log('pause',await page.evaluate(()=>window.__afterlight.state));
console.log('errors',issues);
await fs.writeFile('artifacts/visual-smoke.json',JSON.stringify({issues,telemetry:await page.evaluate(()=>window.__afterlight.telemetry)},null,2));
await browser.close();
