import {CIRCUITS} from './circuits.js';import {VEHICLES} from './vehicle-catalog.js';import {timeString} from './ui.js';
import './history.css';
const tracks=['harbor','coast','mountain'];
const level=r=>r.mode==='time'?'无对手':({easy:'简单',normal:'标准',hard:'困难'}[r.difficulty]||'标准');
const conditions=r=>`${r.theme==='night'?'暗夜':'白天'} · ${level(r)} · ${VEHICLES[r.model].label}`;
export class HistoryScreen{
 constructor(archive,onBack){this.archive=archive;this.page=0;document.getElementById('app').insertAdjacentHTML('beforeend',`<section id="history-screen" hidden><header><div><small>AFTERLIGHT / RACE JOURNAL</small><h1>每一程，都有迹可循。</h1></div><button id="history-back" class="secondary">← 返回</button></header><div id="history-summary"></div><div class="history-filters"><label>赛道 <select id="history-circuit"><option value="all">全部地图</option>${tracks.map(id=>`<option value="${id}">${CIRCUITS[id].name}</option>`).join('')}</select></label><label>模式 <select id="history-mode"><option value="all">全部模式</option><option value="race">两圈竞速</option><option value="time">单圈计时</option></select></label><span id="history-count"></span></div><div id="history-rows"></div><nav class="history-pages"><button id="history-prev" class="secondary">上一页</button><span id="history-page"></span><button id="history-next" class="secondary">下一页</button></nav><section class="history-records"><div class="history-section-title"><small>PERSONAL BEST / 各地图最快总成绩</small><p>竞速与计时独立比较 · 总用时含罚时 · 每项标明实际比赛条件</p></div><div id="history-bests"></div></section><footer id="history-notice"></footer></section>`);this.ui=document.getElementById('history-screen');this.$('history-back').onclick=onBack;for(const id of ['history-circuit','history-mode'])this.$(id).onchange=()=>{this.page=0;this.render();};this.$('history-prev').onclick=()=>{this.page--;this.render();};this.$('history-next').onclick=()=>{this.page++;this.render();};}
 $(id){return document.getElementById(id);}
 open(){this.page=0;this.ui.hidden=false;this.render();this.ui.scrollTop=0;this.$('history-back').focus();}
 close(){this.ui.hidden=true;}
 render(){const all=this.archive.entries,done=all.filter(r=>r.status==='finished');this.$('history-summary').innerHTML=[['赛事记录',all.length],['完赛',done.length],['登上领奖台',done.filter(r=>r.mode==='race'&&r.rankFinal&&r.rank<=3).length],['突破纪录',done.filter(r=>r.newRecord==='improved').length]].map(([a,b])=>`<div><small>${a}</small><strong>${String(b).padStart(2,'0')}</strong></div>`).join('');
 const filtered=all.filter(r=>(this.$('history-circuit').value==='all'||r.circuit===this.$('history-circuit').value)&&(this.$('history-mode').value==='all'||r.mode===this.$('history-mode').value)),pages=Math.max(1,Math.ceil(filtered.length/12));this.page=Math.max(0,Math.min(this.page,pages-1));this.$('history-count').textContent=`${filtered.length} 场赛事`;
 this.$('history-rows').innerHTML=filtered.slice(this.page*12,this.page*12+12).map(r=>`<article class="history-row"><div class="history-rank">${r.status==='retired'?'DNF':r.mode==='time'?'TT':`P${String(r.rank||1).padStart(2,'0')}`}<small>${r.status==='retired'?'中途退出':r.mode==='time'?'已完赛':r.rankFinal?'最终名次':'暂列名次'}</small></div><div class="history-race"><strong>${CIRCUITS[r.circuit].name}</strong><small>${r.mode==='time'?'单圈计时':'两圈竞速'} · ${conditions(r)}</small><time>${new Date(r.startedAt).toLocaleString('zh-CN',{hour12:false})}</time></div><div class="history-time"><strong>${timeString(r.totalTime)}</strong><small>${r.status==='retired'?'退出时累计用时':'完赛总用时'}${r.penalty?` · 含罚时 ${r.penalty} s`:''}</small></div><div class="history-detail"><span>最快圈 ${r.bestLap?timeString(r.bestLap):'—'}</span><span>平均 ${Math.round(r.average)} / 最高 ${Math.round(r.top)} km/h</span><span>超车 ${r.overtakes} 次 ${r.newRecord==='improved'?'<b>↗ 新纪录</b>':r.newRecord==='first'?'<b>首条纪录</b>':''}</span></div></article>`).join('')||'<div class="history-empty"><strong>下一场比赛，将成为你的第一行记录。</strong><p>完成比赛或中途退出后，记录会自动保存到本浏览器。</p></div>';
 this.$('history-page').textContent=`${this.page+1} / ${pages}`;this.$('history-prev').disabled=this.page===0;this.$('history-next').disabled=this.page>=pages-1;
 this.$('history-bests').innerHTML=tracks.map(id=>`<article><small>${CIRCUITS[id].english}</small><h2>${CIRCUITS[id].name}</h2>${['race','time'].map(mode=>{const b=this.archive.best(id,mode);return `<div><span>${mode==='race'?'两圈竞速':'单圈计时'}</span><strong>${b?timeString(b.totalTime):'—'}</strong><small>${b?conditions(b):'暂无完赛纪录'}</small></div>`;}).join('')}</article>`).join('');this.$('history-notice').textContent=this.archive.error?'浏览器存储不可用，当前记录可能无法在刷新后保留。':'记录保存在当前浏览器。历史明细从本次更新起记录；旧版本保存的最快成绩仍可在下方查看。暂列名次表示退出结算时其他车手尚未全部完赛。';}
}
