import {newDesign,normalizeDesign,validateDesign,repairIssue,repairAll,restoreOriginal,recommendedScale,setActualScale,groupDesignIssues,issueRepairable} from './custom-track.js';
import {certifyRaceAsync,designFingerprint} from './custom-race-check.js';
import './track-editor.css';

const $=id=>document.getElementById(id);
const clone=value=>structuredClone(value);
const pointSegmentDistance=(p,a,b)=>{const dx=b[0]-a[0],dz=b[1]-a[1],t=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dz)/(dx*dx+dz*dz||1)));return Math.hypot(p[0]-a[0]-dx*t,p[1]-a[1]-dz*t);};
const choices=[['route','绘制路线'],['move','移动控制点'],['mountain','山地'],['river','河流'],['lake','湖泊'],['pan','平移画布']];

export class TrackEditor{
  constructor(store,{onBack,onSave,onLaunch}){
    this.store=store;this.onBack=onBack;this.onSave=onSave;this.onLaunch=onLaunch;
    document.querySelector('#app').insertAdjacentHTML('beforeend',`<section id="track-editor" hidden aria-label="玩家手绘赛道编辑器">
      <header><button id="editor-back">← 返回</button><div><small>AFTERLIGHT / CREATE YOUR CIRCUIT</small><h1>把你的路线，画成赛道。</h1></div><span id="editor-state">草稿</span></header>
      <nav class="editor-toolbar">${choices.map(([id,label])=>`<button data-editor-tool="${id}">${label}</button>`).join('')}<button id="editor-undo">撤销</button><button id="editor-redo">重做</button><button id="editor-zoom-in">＋</button><button id="editor-zoom-out">－</button></nav>
      <div class="editor-layout"><div class="editor-map"><canvas id="editor-canvas" aria-label="俯视赛道绘图画布"></canvas><div class="editor-map-note">鼠标 / 触屏画线 · 滚轮缩放 · 双指缩放及平移　<span>灰青：原笔迹　金色：赛道　蓝色：系统补绘 / 调整</span></div></div>
      <aside class="editor-sidebar"><label>赛道名称<input id="editor-name" maxlength="40" placeholder="给你的赛道起个名字"></label><div class="editor-inline"><label>道路宽度 <input id="editor-width" type="range" min="8" max="18" step="1"></label><output id="editor-width-label"></output></div>
      <div class="editor-scale"><label for="editor-scale">赛道实际比例 <output id="editor-scale-label">100%</output></label><input id="editor-scale" type="range" min="25" max="350" step="1" value="100"><small>改变赛道在游戏世界中的尺寸；画布缩放只影响观察。</small><button id="editor-scale-recommended">恢复建议比例</button></div>
      <div class="editor-actions"><button id="editor-close-loop">闭合路线</button><button id="editor-preview-loop">预览接缝</button><button id="editor-show-raw">原笔迹对照：开</button></div><p id="editor-hint"></p>
      <div id="editor-stats"></div><h2>需要检查的位置</h2><div id="editor-issues"></div><h2>立体交叉</h2><div id="editor-crossings"></div>
      <div class="editor-repair"><button id="editor-repair-all">一键修复全部</button><button id="editor-restore-raw">恢复原笔迹</button><small id="editor-repair-note">修复会保留原始笔迹，并可用撤销恢复。</small></div>
      <div class="editor-actions"><button id="editor-save">保存草稿</button><button id="editor-export">导出 JSON</button><button id="editor-import">导入 JSON</button><input id="editor-file" type="file" accept="application/json,.json" hidden></div>
      <div class="editor-launch"><button id="editor-drive">3D 试驾</button><button id="editor-time">单车计时</button><button id="editor-race">八车竞速</button></div></aside></div>
      <div class="editor-library" id="editor-library"></div></section>`);
    this.ui=$('track-editor');this.canvas=$('editor-canvas');this.ctx=this.canvas.getContext('2d');this.tool='route';this.scale=.8;this.pan=[0,0];this.rawVisible=true;this.previewLoop=false;this.undo=[];this.redo=[];this.pointers=new Map();this.active=null;this.verifying=false;
    for(const button of this.ui.querySelectorAll('[data-editor-tool]'))button.onclick=()=>this.setTool(button.dataset.editorTool);
    $('editor-back').onclick=()=>this.close();$('editor-undo').onclick=()=>this.restore(this.undo,this.redo);$('editor-redo').onclick=()=>this.restore(this.redo,this.undo);
    $('editor-zoom-in').onclick=()=>{this.scale=Math.min(5,this.scale*1.25);this.draw();};$('editor-zoom-out').onclick=()=>{this.scale=Math.max(.17,this.scale/1.25);this.draw();};
    $('editor-close-loop').onclick=()=>{this.checkpoint();this.design.closed=true;if(!this.design.route)this.design.rawClosed=true;this.evaluate();};
    $('editor-preview-loop').onclick=()=>{this.previewLoop=!this.previewLoop;$('editor-preview-loop').classList.toggle('active',this.previewLoop);if(this.design.raw.length>1)this.hint(`接缝相距 ${Math.round(Math.hypot(this.design.raw[0][0]-this.design.raw.at(-1)[0],this.design.raw[0][1]-this.design.raw.at(-1)[1]))} m；虚线仅供参考，不会自动连接。`);this.draw();};
    $('editor-show-raw').onclick=()=>{this.rawVisible=!this.rawVisible;$('editor-show-raw').textContent=`原笔迹对照：${this.rawVisible?'开':'关'}`;this.draw();};
    $('editor-name').oninput=()=>{this.design.name=$('editor-name').value;};
    $('editor-width').oninput=()=>{this.design.width=Number($('editor-width').value);this.evaluate();};
    $('editor-scale').onpointerdown=()=>{this.scaleGesture=true;this.checkpoint();};$('editor-scale').onpointerup=()=>{this.scaleGesture=false;};$('editor-scale').onchange=()=>{this.scaleGesture=false;};
    $('editor-scale').oninput=()=>{if(!this.scaleGesture)this.checkpoint();this.scaleGesture=true;const adjusted=setActualScale(this.design,this.result,Number($('editor-scale').value)/100);if(adjusted.changed){this.accept(adjusted.design,adjusted.result);this.fitView();}};
    $('editor-scale-recommended').onclick=()=>{const adjusted=setActualScale(this.design,this.result,recommendedScale(this.design,this.result));if(adjusted.changed){this.checkpoint();this.accept(adjusted.design,adjusted.result);this.fitView();}};
    $('editor-repair-all').onclick=()=>this.fixAll();$('editor-restore-raw').onclick=()=>{this.checkpoint();this.accept(restoreOriginal(this.design));this.fitView();};
    $('editor-save').onclick=()=>this.save();$('editor-export').onclick=()=>this.export();$('editor-import').onclick=()=>$('editor-file').click();
    $('editor-file').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{const data=normalizeDesign(JSON.parse(await file.text()));this.open({...data,id:newDesign().id,certification:null});this.hint('赛道已导入为新草稿；八车模式需要重新验证。');}catch(error){this.hint(`导入失败：${error.message}`);}e.target.value='';};
    $('editor-drive').onclick=()=>this.launch('practice');$('editor-time').onclick=()=>this.launch('time');$('editor-race').onclick=()=>this.launch('race');
    this.canvas.addEventListener('pointerdown',e=>this.pointerDown(e));this.canvas.addEventListener('pointermove',e=>this.pointerMove(e));
    for(const event of ['pointerup','pointercancel'])this.canvas.addEventListener(event,e=>this.pointerUp(e));
    this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.scale=Math.max(.17,Math.min(5,this.scale*(e.deltaY>0?.88:1.12)));this.draw();},{passive:false});
    window.addEventListener('resize',()=>{if(!this.ui.hidden)this.draw();});
    this.setTool('route');
  }
  open(design=null){this.design=normalizeDesign(design||newDesign());this.undo=[];this.redo=[];this.scale=.8;this.pan=[0,0];this.previewLoop=false;$('editor-preview-loop').classList.remove('active');this.ui.hidden=false;$('editor-name').value=this.design.name;$('editor-width').value=this.design.width;this.evaluate();this.library();}
  resume(design){this.design=normalizeDesign(design);this.ui.hidden=false;$('editor-name').value=this.design.name;$('editor-width').value=this.design.width;this.evaluate();this.library();}
  close(){this.ui.hidden=true;this.active=null;this.onBack();}
  setTool(value){this.tool=value;this.ui.querySelectorAll('[data-editor-tool]').forEach(b=>b.classList.toggle('active',b.dataset.editorTool===value));this.hint(value==='route'?'从起点连续绘制；抬笔后从末端附近继续。终点靠近起点时可点击“闭合路线”。':value==='move'?'拖动路线上的控制点，修整局部弯道。':`当前工具：${choices.find(c=>c[0]===value)?.[1]}`);}
  hint(value){$('editor-hint').textContent=value;}
  accept(design,result=null){this.design=normalizeDesign(design);$('editor-name').value=this.design.name;$('editor-width').value=this.design.width;$('editor-scale').value=Math.round(this.design.scale*100);this.result=result||validateDesign(this.design);this.render();this.library();}
  fitView(){const points=this.result.centerline||[];if(!points.length)return;const xs=points.map(p=>p[0]),zs=points.map(p=>p[2]??p[1]),w=this.canvas.clientWidth,h=this.canvas.clientHeight;const spanX=Math.max(1,Math.max(...xs)-Math.min(...xs)),spanZ=Math.max(1,Math.max(...zs)-Math.min(...zs));this.scale=Math.max(.04,Math.min(2.5,Math.min(w*.40/spanX,h*.40/spanZ)));this.pan=[-(Math.min(...xs)+Math.max(...xs))/2,-(Math.min(...zs)+Math.max(...zs))/2];this.draw();}
  fixAll(){this.checkpoint();const fixed=repairAll(this.design);if(!fixed.changed){this.restore(this.undo,this.redo);this.hint(this.result.issues.some(issue=>issue.code==='grid')?'周围没有可安全调整出的约 120 m 发车直段；当前仍可单车计时，请手动拉出更长直段后重试。':'当前没有可自动修复的项目；查看问题旁的建议，或继续手动编辑。');return;}this.accept(fixed.design,fixed.result);this.fitView();$('editor-repair-note').textContent=`完成 ${fixed.changed} 项几何修复；原笔迹仍保留在对照层，可撤销整次操作。`;}
  checkpoint(){this.undo.push(clone(this.design));if(this.undo.length>40)this.undo.shift();this.redo=[];}
  restore(from,to){if(!from.length)return;to.push(clone(this.design));this.design=from.pop();$('editor-name').value=this.design.name;$('editor-width').value=this.design.width;this.evaluate();}
  view(){const r=this.canvas.getBoundingClientRect();return {r,w:r.width,h:r.height};}
  screen(p){const {w,h}=this.view();return [w/2+(p[0]+this.pan[0])*this.scale,h/2+(p[1]+this.pan[1])*this.scale];}
  world(e){const {r,w,h}=this.view();return [(e.clientX-r.left-w/2)/this.scale-this.pan[0],(e.clientY-r.top-h/2)/this.scale-this.pan[1]];}
  pointerDown(e){this.canvas.setPointerCapture(e.pointerId);this.pointers.set(e.pointerId,[e.clientX,e.clientY]);if(this.pointers.size>1){this.active={type:'pinch',distance:this.pinchDistance(),scale:this.scale,pan:[...this.pan],center:this.pinchCenter()};return;}
    const point=this.world(e);if(this.tool==='pan'||e.button===1){this.active={type:'pan',start:[e.clientX,e.clientY],pan:[...this.pan]};return;}
    if(this.tool==='move'){const route=this.design.route?.length?this.design.route:this.design.raw;let index=-1,best=18/this.scale;route.forEach((p,i)=>{const d=Math.hypot(p[0]-point[0],p[1]-point[1]);if(d<best){best=d;index=i;}});if(index>=0){this.checkpoint();if(!this.design.route)this.design.route=route.map(p=>[...p]);this.active={type:'move',index};}else this.hint('请按住路线上的控制点拖动。');return;}
    if(this.tool==='route'){const route=this.design.route?.length?this.design.route:this.design.raw;if(this.design.closed){this.hint('已闭合路线；可用“移动控制点”调整，或撤销闭合。');return;}if(route.length&&Math.hypot(point[0]-route.at(-1)[0],point[1]-route.at(-1)[1])>28){this.hint('请从当前末端附近继续，不会自动连一条长直线。');return;}this.checkpoint();if(!route.length)route.push(point);this.active={type:'route'};return;}
    this.checkpoint();this.design.terrain.push({type:this.tool,points:[point]});this.active={type:'terrain',index:this.design.terrain.length-1};
  }
  pinchDistance(){const [a,b]=[...this.pointers.values()];return Math.hypot(a[0]-b[0],a[1]-b[1]);}
  pinchCenter(){const [a,b]=[...this.pointers.values()];return [(a[0]+b[0])/2,(a[1]+b[1])/2];}
  pointerMove(e){if(!this.pointers.has(e.pointerId))return;this.pointers.set(e.pointerId,[e.clientX,e.clientY]);if(!this.active)return;
    if(this.active.type==='pinch'&&this.pointers.size>=2){const now=this.pinchCenter();this.scale=Math.max(.17,Math.min(5,this.active.scale*this.pinchDistance()/this.active.distance));this.pan=[this.active.pan[0]+(now[0]-this.active.center[0])/this.scale,this.active.pan[1]+(now[1]-this.active.center[1])/this.scale];this.draw();return;}
    if(this.active.type==='pan'){this.pan=[this.active.pan[0]+(e.clientX-this.active.start[0])/this.scale,this.active.pan[1]+(e.clientY-this.active.start[1])/this.scale];this.draw();return;}
    const point=this.world(e);
    if(this.active.type==='move'){const route=this.design.route,i=this.active.index,delta=[point[0]-route[i][0],point[1]-route[i][1]];for(const [j,w]of [[i,1],[i-1,.27],[i+1,.27]])if(route[j])route[j]=[route[j][0]+delta[0]*w,route[j][1]+delta[1]*w];this.design.certification=null;this.draw();return;}
    const points=this.active.type==='route'?(this.design.route?.length?this.design.route:this.design.raw):this.design.terrain[this.active.index].points;
    if(!points.length||Math.hypot(point[0]-points.at(-1)[0],point[1]-points.at(-1)[1])>=3)points.push(point);
    this.draw();
  }
  pointerUp(e){this.pointers.delete(e.pointerId);if(this.pointers.size){this.active=null;return;}if(this.active?.type==='terrain'&&this.design.terrain[this.active.index].points.length<3)this.design.terrain.splice(this.active.index,1);this.active=null;this.evaluate();}
  evaluate(){try{this.result=validateDesign(this.design);}catch(error){this.result={status:'draft',issues:[{code:'invalid',severity:'error',point:[0,0],message:error.message,fix:'撤销最近一次编辑'}],crossings:[],centerline:[]};}this.render();}
  render(){const r=this.result;$('editor-state').textContent={draft:'草稿',drive:'可试驾',race:'可正式比赛'}[r.status];$('editor-width-label').textContent=`${this.design.width} m`;$('editor-scale').value=Math.round((this.design.scale||1)*100);$('editor-scale-label').textContent=`${Math.round((this.design.scale||1)*100)}% · ${((r.length||0)/1000).toFixed(2)} km`;
    $('editor-stats').innerHTML=`<div>路线长度 <b>${((r.length||0)/1000).toFixed(2)} km</b></div><div>高差 <b>${Math.round(r.elevation||0)} m</b></div><div>交叉 <b>${r.crossings.length}</b></div><div>弯道难度 <b>${r.difficulty||'待绘制'}</b></div><div>八车发车区 <b>${r.geometryReady?'几何合格':'需检查'}</b></div><div>状态 <b>${$('editor-state').textContent}</b></div>`;
    const groups=groupDesignIssues(r.issues);$('editor-issues').replaceChildren(...groups.map((group,i)=>{const row=document.createElement('div'),text=document.createElement('span'),locate=document.createElement('button'),problem=group.items[0];row.className=`editor-issue-row ${problem.severity}`;text.textContent=`${i+1}. ${problem.message}${group.items.length>1?`（${group.items.length} 处，合并修复）`:''}。建议：${problem.fix}`;locate.className='issue-locate';locate.textContent='定位';locate.onclick=()=>{this.pan=[-group.point[0],-group.point[1]];this.scale=Math.max(this.scale,1.2);this.draw();};row.append(text,locate);if(issueRepairable(problem)){const fix=document.createElement('button');fix.className='issue-fix';fix.textContent='修复';fix.onclick=()=>{this.checkpoint();const fixed=repairIssue(this.design,problem);if(!fixed.changed){this.restore(this.undo,this.redo);this.hint(problem.code==='grid'?'周围没有可安全调整出的约 120 m 发车直段；当前仍可单车计时，请手动拉出更长直段后重试。':'这个问题无法通过局部自动修复；原路线已保留，请拖动控制点微调。');return;}this.accept(fixed.design,fixed.result);this.fitView();};row.append(fix);}else{const action=document.createElement('small');action.className='issue-manual';action.textContent=problem.code==='ai-check'?'待 AI 验证':'需手动';row.append(action);}return row;}));
    if(!r.issues.length)$('editor-issues').textContent='未发现阻止试驾的问题。';
    $('editor-crossings').replaceChildren(...r.crossings.map((c,i)=>{const b=document.createElement('button');b.textContent=`交叉 ${i+1}：第 ${Math.round(c.first*8)} m / ${Math.round(c.second*8)} m · ${c.upper==='first'?'第一次上层':'第二次上层'} · 净空 ${Math.round(c.clearance||0)} m`;b.onclick=()=>{this.checkpoint();this.design.overrides[c.id]={upper:c.upper==='first'?'second':'first',point:c.point};this.evaluate();};return b;}));
    if(!r.crossings.length)$('editor-crossings').textContent='没有立体交叉。';
    $('editor-drive').disabled=r.status==='draft';$('editor-time').disabled=r.status==='draft';$('editor-race').disabled=!r.geometryReady;$('editor-close-loop').disabled=this.design.closed||this.design.raw.length<8;this.draw();}
  draw(){if(this.ui.hidden)return;const {r,w,h}=this.view(),dpr=Math.min(2,window.devicePixelRatio||1);this.canvas.width=Math.round(w*dpr);this.canvas.height=Math.round(h*dpr);this.ctx.setTransform(dpr,0,0,dpr,0,0);const c=this.ctx;c.fillStyle='#16272b';c.fillRect(0,0,w,h);
    c.strokeStyle='#ffffff0c';c.lineWidth=1;for(let x=w/2+(this.pan[0]%100)*this.scale;x<w;x+=100*this.scale){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();}for(let y=h/2+(this.pan[1]%100)*this.scale;y<h;y+=100*this.scale){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();}
    for(const region of this.design.terrain){const points=region.points;if(!points.length)continue;c.beginPath();points.forEach((p,i)=>{const [x,y]=this.screen(p);i?c.lineTo(x,y):c.moveTo(x,y);});if(region.type!=='river'&&points.length>=3)c.closePath();c.fillStyle={mountain:'#9a80674d',river:'#3abbd84d',lake:'#3abbd85a'}[region.type];c.strokeStyle={mountain:'#c8a277',river:'#60d2ea',lake:'#60d2ea'}[region.type];c.lineWidth=region.type==='river'?22*this.scale:2;if(region.type==='river')c.stroke();else{c.fill();c.stroke();}}
    const line=(points,color,width,closed=false)=>{if(points.length<2)return;c.beginPath();points.forEach((p,i)=>{const [x,y]=this.screen([p[0],p.at(-1)]);i?c.lineTo(x,y):c.moveTo(x,y);});if(closed)c.closePath();c.strokeStyle=color;c.lineWidth=width;c.lineJoin='round';c.lineCap='round';c.stroke();};
    if(this.rawVisible)line(this.design.raw,'#76aeb2aa',2,this.design.rawClosed);
    if(this.previewLoop&&!this.design.closed&&this.design.raw.length>1){const a=this.screen(this.design.raw.at(-1)),b=this.screen(this.design.raw[0]);c.save();c.setLineDash([7,7]);c.strokeStyle='#ff9d84';c.lineWidth=2;c.beginPath();c.moveTo(...a);c.lineTo(...b);c.stroke();c.restore();}
    line(this.result.centerline,'#0c171c',Math.max(5,this.design.width*this.scale),this.design.closed);
    line(this.result.centerline,this.design.route?'#e4c37d':'#e3b975',Math.max(2,this.design.width*this.scale*.6),this.design.closed);
    if(this.design.route?.length&&this.design.raw.length>1&&this.result.centerline.length>1){
      const sourceStep=Math.max(1,Math.floor(this.design.raw.length/350)),source=this.design.raw.filter((_,i)=>i%sourceStep===0),nearest=point=>{let best=Infinity;for(let i=1;i<source.length;i++)best=Math.min(best,pointSegmentDistance(point,source[i-1],source[i]));return best;},points=this.result.centerline;
      c.beginPath();for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length],mid=[(a[0]+b[0])/2,(a.at(-1)+b.at(-1))/2];if(nearest(mid)>8){const [ax,ay]=this.screen([a[0],a.at(-1)]),[bx,by]=this.screen([b[0],b.at(-1)]);c.moveTo(ax,ay);c.lineTo(bx,by);}}c.strokeStyle='#56c8e0';c.lineWidth=Math.max(2,this.design.width*this.scale*.24);c.stroke();
    }
    for(const hit of this.result.crossings){const at=Math.round(hit.upper==='first'?hit.first:hit.second),points=this.result.centerline,n=points.length;if(n>8){const segment=Array.from({length:9},(_,i)=>points[(at+i-4+n)%n]);line(segment,'#11262c',Math.max(8,this.design.width*this.scale+4));line(segment,'#e8eee8',Math.max(3,this.design.width*this.scale*.6));}}
    if(this.design.raw.length){for(const [i,p]of this.design.raw.entries())if(i%Math.max(1,Math.floor(this.design.raw.length/80))===0){const [x,y]=this.screen(p);c.fillStyle='#d8edea';c.beginPath();c.arc(x,y,3,0,Math.PI*2);c.fill();}const [rx,ry]=this.screen(this.design.raw[0]);c.strokeStyle='#8cbec0';c.lineWidth=2;c.beginPath();c.arc(rx,ry,5,0,Math.PI*2);c.stroke();if(!this.design.closed){const [ex,ey]=this.screen(this.design.raw.at(-1));c.strokeStyle='#ff9d84';c.beginPath();c.arc(ex,ey,8,0,Math.PI*2);c.stroke();}}
    if(this.result.centerline.length){const start=this.result.centerline[0],[sx,sy]=this.screen([start[0],start.at(-1)]);c.fillStyle='#f5c674';c.beginPath();c.arc(sx,sy,7,0,Math.PI*2);c.fill();c.fillStyle='#172127';c.font='bold 10px sans-serif';c.textAlign='left';c.fillText('START',sx+11,sy+4);}
    for(const [i,hit]of this.result.crossings.entries()){const [x,y]=this.screen(hit.point);c.fillStyle='#f3c270';c.beginPath();c.arc(x,y,11,0,Math.PI*2);c.fill();c.fillStyle='#172127';c.font='12px sans-serif';c.textAlign='center';c.fillText(String(i+1),x,y+4);}
    for(const problem of this.result.issues){const [x,y]=this.screen(problem.point);c.strokeStyle=problem.severity==='error'?'#ff766e':'#f4ca72';c.lineWidth=3;c.beginPath();c.arc(x,y,14,0,Math.PI*2);c.stroke();}
  }
  save(){try{this.design=this.store.save(this.design);this.hint('草稿已保存在当前浏览器。');this.library();this.onSave(this.design,this.result);return true;}catch(error){this.hint(`保存失败：${error.message}`);return false;}}
  export(){const blob=new Blob([JSON.stringify(this.design,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${this.design.name||'赛道'}.afterlight.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async launch(mode){if(this.verifying||this.result.status==='draft'||mode==='race'&&!this.result.geometryReady)return;
    if(mode==='race'&&!this.result.raceReady){this.verifying=true;$('editor-race').disabled=true;this.hint('正在模拟八车完整比赛，检查 AI、发车与计圈…');const source=structuredClone(this.design),signature=designFingerprint(source);await new Promise(resolve=>setTimeout(resolve,30));const check=await certifyRaceAsync(source,this.result,level=>this.hint(`正在验证 ${level} 难度：八车两圈…`));this.verifying=false;if(this.ui.hidden||this.design.id!==source.id||designFingerprint(this.design)!==signature){this.evaluate();this.hint('验证期间设计发生变化，请重新运行八车检查。');return;}if(!check.passed){this.result.issues.push({code:'ai-check-failed',severity:'warning',point:check.point,message:check.reason,fix:'调整附近弯道、坡道或发车区，然后重试'});this.render();this.hint(`暂不开放八车：${check.reason}`);return;}this.design.certification={fingerprint:signature,passed:true,checkedAt:new Date().toISOString()};this.evaluate();this.hint(`八车均完成两圈，最慢完赛 ${Math.round(check.slowest)} 秒。`);}
    if(!this.save())return;this.ui.hidden=true;this.onLaunch(this.design,this.result,mode);}
  library(){const root=$('editor-library');root.replaceChildren();const title=document.createElement('h2');title.textContent=`我的赛道 · ${this.store.items.length}`;root.append(title);for(const design of this.store.items){const row=document.createElement('div'),label=document.createElement('span'),edit=document.createElement('button'),remove=document.createElement('button');label.textContent=`${design.name} · ${{draft:'草稿',drive:'可试驾',race:'可比赛'}[validateDesign(design).status]}`;edit.textContent='重新编辑';edit.onclick=()=>this.open(design);remove.textContent='删除';remove.onclick=()=>{if(!confirm(`删除「${design.name}」的设计数据？`))return;this.store.delete(design.id);this.onSave(null,null,design.id);if(this.design.id===design.id)this.open();else this.library();};row.append(label,edit,remove);root.append(row);}}
}
