import {VEHICLE_LIST,PAINTS} from './vehicle-catalog.js';
const mark=`<svg class="brand-mark" viewBox="0 0 40 36" fill="none" aria-hidden="true"><path d="M3 31 18 4h5L9 31H3Z" fill="currentColor"/><path d="m20 12 5-8 14 27h-7l-6-12-7 12h-7l8-19Z" fill="#e4b76c"/></svg>`;
const brand=`<div class="brand">${mark}<div><div class="brand-name">AFTERLIGHT</div><div class="brand-sub">逐 光 · COASTLINE</div></div></div>`;
export function paintButtons(){return PAINTS.map((p,i)=>`<button class="swatch ${i===0?'selected':''}" style="--swatch:${p.color}" data-paint="${p.color}" aria-label="车漆 ${p.name}"></button>`).join('');}
export function mountUI() {
 document.querySelector('#app').innerHTML=`
 <canvas id="scene" aria-label="逐光三维赛车场景"></canvas>
 <div class="loading" id="loading"><div class="loading-inner"><div class="loading-title">AFTERLIGHT</div><small>正在准备海岸、光线与引擎</small><div class="loading-bar"><i></i></div><small id="loading-status">构建原创三维场景</small></div></div>
 <main class="screen menu" id="menu">
  <header class="topbar">${brand}<nav class="topnav"><button class="active" id="nav-race">竞速 / RACE</button><button id="nav-studio">汽车鉴赏 / GARAGE</button><button id="nav-settings">设置 / SETTINGS</button></nav><span class="edition"><i class="small-dot"></i>AFTERLIGHT / 03 CIRCUITS</span></header>
  <section class="hero"><div class="eyebrow">THE GOLDEN COAST · VOL. 01</div><h1>CHASE<br>THE <em>LIGHT.</em></h1><h2 class="hero-cn">逐光 · 金潮海岸</h2><p>沿着海岸的曲线，驶向落日。<br>一段纯粹的公路，一场属于你的竞速。</p><div class="hero-actions"><button class="primary" id="play">开始竞速 <span>↗</span></button><button class="secondary" id="showroom">鉴赏车辆</button></div><div class="hero-bottom"><span id="track-length">2.55 KM 海岸环线</span><span>8 位车手</span><span>黄金时刻</span></div></section>
  <aside class="location"><small>LANWAN, THE GOLDEN COAST</small><strong>岚湾 · 海岸公路</strong><span>晴间多云 &nbsp; / &nbsp; 18:42 &nbsp; / &nbsp; 24°C</span></aside>
  <svg class="compass" viewBox="0 0 30 60" fill="none"><text x="15" y="10" fill="currentColor" font-size="8" text-anchor="middle">N</text><path d="m15 20 6 21-6-4-6 4 6-21Z" stroke="currentColor"/><path d="M15 37v16" stroke="currentColor"/></svg>
  <div class="car-caption"><small>YOUR NEXT DRIVE</small><strong id="hero-car-name">AURORA GT</strong><span id="hero-car-sub">AWD / GRAND TOURER</span></div>
  <section class="garage-entry"><button class="primary" id="open-garage">进入车库 / 选择车辆 ↗</button><button class="secondary" id="open-history">历史记录 / RACE JOURNAL ↗</button><button class="secondary" id="open-leaderboard">全球排行榜 / WORLD RECORDS ↗</button><div><small>THE COASTAL COLLECTION</small>${VEHICLE_LIST.length} 辆原创座驾 · 选择你的下一程</div></section>
  <footer class="footer"><span><kbd>W A S D</kbd> 驾驶 &nbsp; <kbd>SPACE</kbd> 手刹 &nbsp; <kbd>C</kbd> 镜头 &nbsp; <kbd>ESC</kbd> 暂停</span><span>ORIGINAL MACHINES. OPEN COAST. &nbsp; © AFTERLIGHT</span></footer>
 </main>
 <section class="screen studio" id="studio" hidden><header class="topbar">${brand}<button class="secondary" id="studio-back">← 返回海岸</button></header><aside class="studio-panel"><div class="eyebrow">MACHINE / 01</div><h2 id="studio-name">AURORA GT</h2><p id="studio-desc">曲面、金属与光线。<br>为海岸公路而生的原创 GT。</p><div class="studio-stats"><div><small>模拟 0–100 km/h</small><b id="studio-power">—</b></div><div><small>模拟质量 / KG</small><b id="studio-mass">1540 KG</b></div><div><small>游戏极速上限</small><b id="studio-speed">295 KM/H</b></div><div><small>DRIVETRAIN</small><b id="studio-layout">AWD</b></div></div></aside><div class="studio-detail"><strong>CRAFTED IN THREE DIMENSIONS</strong><br>原创参数化曲面 · 多层车漆<br>独立轮组 · 灯具与座舱结构<br><span id="mesh-stat"></span></div><div class="studio-tools"><button class="active" data-view="orbit">全景环绕</button><button data-view="front">前脸细节</button><button data-view="wheel">轮组特写</button><button data-view="rear">尾部设计</button><button id="export-model">导出 GLB ↓</button><button id="studio-choose">选择车辆 ↗</button></div><div class="studio-colors paint-group">${paintButtons()}</div><div class="studio-help">拖动旋转 · 滚轮缩放 · 点击部位切换镜头</div></section>
 <section class="screen hud" id="hud" hidden><div class="hud-top"><div><div class="position-block"><b id="position">8</b><span id="competitors">/ 8</span></div><div class="position-label">POSITION / 当前名次</div></div><div class="lap-block"><div><small id="lap-label">LAP / 圈数</small><b id="lap">1 / 2</b></div><div><small>RACE TIME / 用时</small><b id="timer">00:00.000</b></div></div></div><div class="hud-route"><strong id="route-title">金潮海岸</strong><small id="route-subtitle">GOLDEN COAST CIRCUIT</small></div><div class="progress-track"><i id="race-progress"></i></div><div class="leaderboard" id="leaderboard"></div><div class="mini-wrap"><canvas class="minimap" id="minimap" width="360" height="360"></canvas><div class="mini-caption">THE GOLDEN COAST / <span id="distance-left">2.55 KM</span></div></div><div class="speedometer"><div class="speed-number"><small id="gear">N</small><span id="speed">000</span></div><div class="speed-unit">KILOMETRES PER HOUR</div><div class="rpm-track"><i id="rpm"></i></div><div class="assist-label"><span id="drive-assist">TCS · ABS</span><span id="hud-car">AURORA GT</span></div></div><div class="race-controls"><kbd>W / ↑</kbd> 油门 <kbd>S / ↓</kbd> 刹车 <kbd>A D</kbd> 转向 <kbd>空格</kbd> 手刹<br><kbd>C</kbd> 镜头 <kbd>L</kbd> 车灯 <kbd>R</kbd> 复位 +3 秒 <kbd>ESC</kbd> 暂停 <kbd>M</kbd> 静音</div><div class="mobile-controls"><div class="mobile-group"><button data-touch="left">◀</button><button data-touch="right">▶</button></div><div class="mobile-group"><button data-touch="brake">刹</button><button data-touch="throttle">油</button></div></div><div class="countdown" id="countdown" hidden></div><div class="event-banner" id="event-banner" hidden></div></section>
 <div class="modal-backdrop" id="race-modal" hidden><section class="modal" role="dialog" aria-modal="true" aria-labelledby="race-title"><div class="modal-head"><div><small>AFTERLIGHT / RACE BRIEFING</small><h2 id="race-title">下一站，金潮海岸。</h2></div><button class="icon-button" data-close="race-modal" aria-label="关闭">×</button></div><canvas class="track-map" id="brief-map" width="800" height="190"></canvas><div class="launch-info"><span id="brief-distance">2.55 KM · 2 圈</span><span id="brief-atmosphere">干燥路面 · 黄金时刻</span></div><label class="field"><span>赛事模式<small>完整封闭环线</small></span><select id="mode"><option value="race">快速竞速 · 8 车</option><option value="time">计时挑战 · 单车</option></select></label><label class="field"><span>赛道氛围<small>三条赛道，各有昼夜风景</small></span><select id="theme"><option value="day">白天 · 黄金时刻</option><option value="night">暗夜 · 霓虹光影</option><option value="random">随机 · 交给命运</option></select></label><label class="field"><span>对手难度<small>影响驾驶节奏与弯道速度</small></span><select id="difficulty"><option value="easy">悠游 · 简单</option><option value="normal" selected>逐光 · 标准</option><option value="hard">极限 · 困难</option></select></label><button class="primary" id="start-race">驶入发车区 <span>→</span></button><p class="modal-note">WASD / 方向键驾驶，手柄左摇杆转向，RT 油门、LT 刹车。暗夜模式会启用路灯、霓虹路侧标记与星空月光。</p></section></div>
 <div class="modal-backdrop" id="settings-modal" hidden><section class="modal" role="dialog" aria-modal="true" aria-labelledby="settings-title"><div class="modal-head"><div><small>MAKE IT YOUR DRIVE</small><h2 id="settings-title">驾驶偏好</h2></div><button class="icon-button" data-close="settings-modal" aria-label="关闭">×</button></div><label class="field"><span>画质<small>优先保证行驶流畅</small></span><select id="quality"><option value="high">高 · 精细阴影</option><option value="medium" selected>标准 · 推荐</option><option value="low">流畅 · 低开销</option></select></label><label class="field"><span>游戏声音<small>引擎、风噪、轮胎与倒计时</small></span><input type="checkbox" id="sound-enabled" checked></label><label class="field"><span>中文赛事播报<small>本地合成语音，可独立关闭</small></span><input type="checkbox" id="voice-enabled" checked></label><label class="field"><span>速度镜头<small>随车速轻微调整视野</small></span><input type="checkbox" id="dynamic-camera" checked></label><label class="field"><span>性能信息<small>显示实时帧率与绘制数量</small></span><input type="checkbox" id="show-fps"></label><p class="modal-note">比赛成绩保存在本地；启用在线排行榜后，完赛用时、名次、匿名昵称及地区会提交到全球榜。</p></section></div>
 <div class="modal-backdrop pause-overlay" id="pause-modal" hidden><section class="modal" role="dialog" aria-modal="true"><div class="modal-head"><div><small>TAKE A BREATH</small><h2>比赛已暂停</h2></div></div><div class="pause-actions"><button class="primary" id="resume">继续驾驶 →</button><button class="secondary" id="restart">重新发车</button><button class="secondary" id="pause-settings">驾驶设置</button><button class="secondary" id="quit">返回主菜单</button></div></section></div>
 <div class="modal-backdrop result" id="result-modal" hidden><section class="modal" role="dialog" aria-modal="true"><div class="eyebrow">THE GOLDEN COAST / CLASSIFIED</div><div id="record-badge" hidden></div><div class="result-title" id="result-title">CHASE COMPLETE.</div><p class="result-sub" id="result-sub">你与海岸，共享了这一道光。</p><div class="result-stats"><div><small>POSITION / 名次</small><strong id="result-position">01 / 08</strong></div><div><small>TOTAL / 总用时</small><strong id="result-time">00:00.000</strong></div><div><small>BEST LAP / 最快圈</small><strong id="result-lap">00:00.000</strong></div></div><div class="result-list" id="result-list"></div><p class="modal-note" id="record-note"></p><p class="leaderboard-upload" id="leaderboard-upload" role="status"></p><button class="leaderboard-retry" id="leaderboard-retry" hidden>重试上传成绩</button><div class="result-actions"><button class="secondary" id="result-home">返回车库</button><button class="primary" id="result-retry">再跑一次 ↗</button></div></section></div>
 <div class="toast" id="toast" hidden></div><div class="fps" id="fps" hidden></div>`;
 document.querySelector('#hud').insertAdjacentHTML('beforeend',`
  <aside class="telemetry-panel" id="telemetry-panel"><div class="telemetry-head"><span>LIVE TELEMETRY</span><i></i></div><div class="silver-rank"><span class="rank-prefix">P</span><strong id="silver-rank">08</strong><span class="rank-total" id="silver-total">/08</span></div><div class="pass-label" id="pass-label">当前排名 · POSITION</div><div class="telemetry-grid"><div><small>平均时速 / AVG</small><strong id="stat-average">000</strong><span> KM/H</span></div><div><small>最高时速 / MAX</small><strong id="stat-top">000</strong><span> KM/H</span></div><div><small>超车 / OVERTAKES</small><strong id="stat-passes">00</strong></div><div><small>圈数 / LAP</small><strong id="stat-lap">01</strong><span id="stat-laps"> / 02</span></div></div><div class="telemetry-scan"></div></aside>`);
 document.querySelector('#app').insertAdjacentHTML('beforeend',`
  <div class="finish-cinema" id="finish-cinema" hidden><div class="cinema-top"><span>AFTERLIGHT / FINISH SEQUENCE</span><span id="finish-status">FINISH LINE CROSSED</span></div><div class="cinema-bottom"><div><small>THE GOLDEN COAST</small><strong>CHASE COMPLETE.</strong></div><button id="skip-cinema">跳过运镜 →</button></div></div>`);
 document.querySelector('#result-modal .modal').insertAdjacentHTML('afterbegin','<div class="result-scan"></div><div class="result-orbit-label">RACE DATA / SYNCHRONIZED</div><div class="result-hero-rank" id="result-hero-rank">P01</div>');
 document.querySelector('#result-list').insertAdjacentHTML('beforebegin',`<div class="result-performance"><div><small>AVERAGE / 平均时速</small><strong id="result-average">0</strong><span> KM/H</span></div><div><small>PEAK / 最高时速</small><strong id="result-top">0</strong><span> KM/H</span></div><div><small>OVERTAKES / 超车</small><strong id="result-passes">0</strong><span> 次</span></div></div>`);
 document.querySelector('#brief-map').insertAdjacentHTML('beforebegin',`<label class="field circuit-field"><span>选择赛道<small>官方赛道与玩家创作</small></span><select id="circuit"><option value="harbor">港口城区 · 铬湾港城</option><option value="coast">海岸公路 · 金潮海岸</option><option value="mountain">山地道路 · 岚脊天路</option></select></label><div class="custom-track-actions"><button id="create-track" type="button">＋ 创建赛道</button><button id="my-tracks" type="button">我的赛道 ↗</button></div>`);
 document.querySelector('#brief-map').insertAdjacentHTML('afterend',`<div class="circuit-profile"><p id="circuit-description"></p><canvas id="elevation-profile" width="800" height="65" aria-label="赛道海拔剖面"></canvas><small id="circuit-elevation"></small></div>`);
 return id=>document.getElementById(id);
}

export function timeString(seconds){
 if(!Number.isFinite(seconds))return '—';
 const ms=Math.round(Math.max(0,seconds)*1000);
 return `${String(Math.floor(ms/60000)).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}.${String(ms%1000).padStart(3,'0')}`;
}
