// Single source for geometry, driving, garage cards, paint and audio.
// Speed caps / mass / grip are GAME tuning values, never manufacturer claims.
export const VEHICLE_LIST = [
 {id:'aurora',name:'曙光 GT',label:'AURORA GT',subtitle:'曙光 · GRAND TOURER',drivetrain:'AWD',layout:'AWD · GRAND TOURER',mass:1540,topSpeed:82,acceleration:10.6,braking:25,grip:15.2,agility:1,slipResponse:15,handbrakeResponse:4.2,color:'#b8d9cf',wheelbase:2.72,length:4.61,halfWidth:.99,wheelRadius:.373,engine:'gt',design:{wheelDesign:{spokes:10,deep:.008,spokeWidth:.024}},description:'均衡四驱 GT。稳定的车身姿态与扎实的出弯牵引，适合长距离海岸竞速。'},
 {id:'kasumi',name:'雾刃 R',label:'KASUMI R',subtitle:'雾刃 · CLUB SPORT',drivetrain:'RWD',layout:'RWD · LIGHTWEIGHT',mass:1210,topSpeed:77,acceleration:10.1,braking:25,grip:16.4,agility:1.10,slipResponse:11,handbrakeResponse:4.2,color:'#ebaa66',wheelbase:2.62,length:4.34,halfWidth:.93,wheelRadius:.373,engine:'light',design:{wheelDesign:{spokes:8,deep:.018,spokeWidth:.029}},description:'轻量俱乐部跑车。较高的抓地力和迅捷转向，擅长连续弯道。'},
 {id:'vesper',name:'暮星 X',label:'VESPER X',subtitle:'暮星 · MID ENGINE',drivetrain:'RWD',layout:'MR · SUPERCAR',mass:1435,topSpeed:88,acceleration:11.7,braking:25,grip:14.3,agility:.92,slipResponse:15,handbrakeResponse:4.2,color:'#b4bbc7',wheelbase:2.8,length:4.67,halfWidth:1.015,wheelRadius:.373,engine:'supercar',design:{wheelDesign:{spokes:12,deep:.026,spokeWidth:.019}},description:'前移座舱与中置布局。高速性能强劲，极限弯道需要克制油门。'},
 {id:'nightslash',name:'夜刃',label:'NIGHTSLASH',subtitle:'夜刃 · HERITAGE COUPÉ',drivetrain:'RWD',layout:'RWD · HERITAGE COUPÉ',mass:1280,topSpeed:78,acceleration:10.3,braking:26,grip:15.8,agility:1.12,slipResponse:12.5,handbrakeResponse:6.5,color:'#618ba0',wheelbase:2.65,length:4.38,halfWidth:.975,wheelRadius:.346,engine:'light',premium:true,description:'紧凑双门、方正座舱与深凹六辐轮圈。灵活转向，后轮滑移渐进、容易收回。',design:{nose:2.22,tail:-2.16,frontAxle:1.29,rearAxle:-1.36,roofY:1.36,roofFront:.06,roofBack:-.90,windBase:.66,rearBase:-1.44,roofHalf:.65,cabinShift:-.07,frontTire:.275,rearTire:.285,wheelDesign:{spokes:6,deep:.065,spokeWidth:.043}}},
 {id:'tempest',name:'雷暴',label:'TEMPEST',subtitle:'雷暴 · MODERN MUSCLE',drivetrain:'RWD',layout:'FR · MUSCLE COUPÉ',mass:1780,topSpeed:85,acceleration:13,braking:22.2,grip:14.2,agility:.86,slipResponse:14.5,handbrakeResponse:4.8,color:'#885547',wheelbase:2.91,length:5.02,halfWidth:1.045,wheelRadius:.385,engine:'muscle',premium:true,description:'长机盖、后移低顶座舱与宽后胎。直线加速有力，转向沉稳，入弯前需要提前制动。',design:{muscle:true,nose:2.60,tail:-2.42,frontAxle:1.42,rearAxle:-1.49,roofY:1.37,roofFront:-.27,roofBack:-1.12,windBase:.42,rearBase:-1.86,roofHalf:.67,cabinShift:-.40,frontTire:.30,rearTire:.355,widths:[[-2.42,.90],[-2.18,1],[-1.49,1],[-.7,.96],[.4,.93],[1.42,1],[2.32,.97],[2.6,.92]],tops:[[-2.42,.96],[-2.12,1.02],[-1.49,1.04],[-.4,1.02],[.42,1.01],[1.4,.98],[2.3,.91],[2.6,.88]],wheelDesign:{spokes:5,deep:.048,spokeWidth:.064}}},
];
// Fab visual-only candidate. It deliberately inherits Aurora's physics tuning
// and collision dimensions so adding it to the collection does not retune play.
export const GREEN_BUG_ID='green-bug';
export const GREEN_BUG={...VEHICLE_LIST[0],id:GREEN_BUG_ID,name:'Green Bug',label:'GREEN BUG',subtitle:'GREEN BUG · STYLIZED SCI-FI',layout:'AWD · AURORA GT HANDLING',description:'Fab 免费车型视觉候选。沿用 Aurora GT 的驾驶与碰撞参数。',paintable:false};
// Keep this original five-car list for race opponents and benchmarks.
export const GARAGE_VEHICLE_LIST=[...VEHICLE_LIST,GREEN_BUG];
export const VEHICLES=Object.fromEntries(GARAGE_VEHICLE_LIST.map(v=>[v.id,v]));
export const CAR_SPECS=GARAGE_VEHICLE_LIST;
export const PAINTS=[{color:'#b8d9cf',name:'海盐绿'},{color:'#d9d6cc',name:'珍珠白'},{color:'#d49a60',name:'香槟金'},{color:'#547d91',name:'深海蓝'},{color:'#983e39',name:'赤陶红'},{color:'#30383d',name:'石墨黑'}];
export const getVehicle=id=>VEHICLES[id]||GARAGE_VEHICLE_LIST[0];
